spring:
  application:
    name: hotel_booking

  datasource:
    url: jdbc:postgresql://acela.proxy.rlwy.net:24427/railway
    username: postgres
    password: ktVCMUIoTvtOrwqdKtZKnFFXupglQrEI

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true